services:
  - type: web
    name: pyquest-backend
    runtime: python
    region: singapore
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: CORS_ORIGINS
        value: "*"
      - key: FIREBASE_PROJECT_ID
        value: nopphonapp-d0c5b
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "false"
      - key: DEV_AUTH_BYPASS
        value: "false"
      - key: ADMIN_EMAILS
        value: "nopphon052k@gmail.com,admin@pyquest.com"
