// Comprehensive Python completions for Monaco Editor in PyQuest

export interface CompletionItemData {
  label: string;
  kind: "Function" | "Method" | "Snippet" | "Keyword" | "Module" | "Variable";
  insertText: string;
  documentation: string;
  isSnippet?: boolean;
}

export const PYTHON_COMPLETIONS: CompletionItemData[] = [
  // ==========================================
  // 1. BUILT-IN FUNCTIONS
  // ==========================================
  {
    label: "print",
    kind: "Function",
    insertText: "print(${1:value})",
    documentation: "print(*values, sep=' ', end='\\n', file=sys.stdout, flush=False)\nPrints values to a stream or to sys.stdout.",
    isSnippet: true,
  },
  {
    label: "input",
    kind: "Function",
    insertText: "input(${1:})",
    documentation: "input([prompt]) -> str\nReads a string from standard input. The trailing newline is stripped.",
    isSnippet: true,
  },
  {
    label: "len",
    kind: "Function",
    insertText: "len(${1:obj})",
    documentation: "len(s) -> int\nReturn the number of items in a container (string, list, tuple, dict, set, etc.).",
    isSnippet: true,
  },
  {
    label: "range",
    kind: "Function",
    insertText: "range(${1:stop})",
    documentation: "range(stop) or range(start, stop[, step]) -> range object\nGenerates a sequence of numbers from start (inclusive) to stop (exclusive).",
    isSnippet: true,
  },
  {
    label: "int",
    kind: "Function",
    insertText: "int(${1:x})",
    documentation: "int(x=0) or int(x, base=10) -> integer\nConverts a number or string to an integer.",
    isSnippet: true,
  },
  {
    label: "str",
    kind: "Function",
    insertText: "str(${1:object})",
    documentation: "str(object='') -> str\nCreates a new string object from the given object.",
    isSnippet: true,
  },
  {
    label: "float",
    kind: "Function",
    insertText: "float(${1:x})",
    documentation: "float(x=0.0) -> float\nConverts a string or number to a floating point number.",
    isSnippet: true,
  },
  {
    label: "bool",
    kind: "Function",
    insertText: "bool(${1:x})",
    documentation: "bool(x) -> bool\nReturns True when the argument x is true, False otherwise.",
    isSnippet: true,
  },
  {
    label: "list",
    kind: "Function",
    insertText: "list(${1:iterable})",
    documentation: "list([iterable]) -> new list\nBuilt-in mutable sequence.",
    isSnippet: true,
  },
  {
    label: "dict",
    kind: "Function",
    insertText: "dict(${1:})",
    documentation: "dict() -> new empty dictionary\nBuilt-in key-value mapping type.",
    isSnippet: true,
  },
  {
    label: "set",
    kind: "Function",
    insertText: "set(${1:iterable})",
    documentation: "set([iterable]) -> new set object\nBuilt-in unordered collection of unique elements.",
    isSnippet: true,
  },
  {
    label: "tuple",
    kind: "Function",
    insertText: "tuple(${1:iterable})",
    documentation: "tuple([iterable]) -> tuple\nBuilt-in immutable sequence.",
    isSnippet: true,
  },
  {
    label: "sum",
    kind: "Function",
    insertText: "sum(${1:iterable})",
    documentation: "sum(iterable, start=0) -> value\nSums start and the items of an iterable from left to right.",
    isSnippet: true,
  },
  {
    label: "max",
    kind: "Function",
    insertText: "max(${1:iterable})",
    documentation: "max(iterable, *[, key, default]) or max(arg1, arg2, *args, key=None) -> value\nWith a single iterable argument, return its biggest item.",
    isSnippet: true,
  },
  {
    label: "min",
    kind: "Function",
    insertText: "min(${1:iterable})",
    documentation: "min(iterable, *[, key, default]) or min(arg1, arg2, *args, key=None) -> value\nWith a single iterable argument, return its smallest item.",
    isSnippet: true,
  },
  {
    label: "abs",
    kind: "Function",
    insertText: "abs(${1:x})",
    documentation: "abs(number) -> number\nReturn the absolute value of the argument.",
    isSnippet: true,
  },
  {
    label: "round",
    kind: "Function",
    insertText: "round(${1:number}, ${2:ndigits})",
    documentation: "round(number[, ndigits]) -> number\nRound a number to a given precision in decimal digits.",
    isSnippet: true,
  },
  {
    label: "enumerate",
    kind: "Function",
    insertText: "enumerate(${1:iterable})",
    documentation: "enumerate(iterable, start=0) -> enumerate object\nYield pairs containing a count (from start) and a value yielded by the iterable.",
    isSnippet: true,
  },
  {
    label: "zip",
    kind: "Function",
    insertText: "zip(${1:iter1}, ${2:iter2})",
    documentation: "zip(*iterables, strict=False) -> zip object\nYield tuples until an input is exhausted.",
    isSnippet: true,
  },
  {
    label: "sorted",
    kind: "Function",
    insertText: "sorted(${1:iterable}, key=${2:None}, reverse=${3:False})",
    documentation: "sorted(iterable, /, *, key=None, reverse=False) -> new list\nReturn a new list containing all items from the iterable in ascending order.",
    isSnippet: true,
  },
  {
    label: "map",
    kind: "Function",
    insertText: "map(${1:function}, ${2:iterable})",
    documentation: "map(func, *iterables) -> map object\nMake an iterator that computes the function using arguments from each of the iterables.",
    isSnippet: true,
  },
  {
    label: "filter",
    kind: "Function",
    insertText: "filter(${1:function}, ${2:iterable})",
    documentation: "filter(function or None, iterable) -> filter object\nReturn an iterator yielding those items of iterable for which function(item) is true.",
    isSnippet: true,
  },
  {
    label: "any",
    kind: "Function",
    insertText: "any(${1:iterable})",
    documentation: "any(iterable) -> bool\nReturn True if bool(x) is True for any x in the iterable.",
    isSnippet: true,
  },
  {
    label: "all",
    kind: "Function",
    insertText: "all(${1:iterable})",
    documentation: "all(iterable) -> bool\nReturn True if bool(x) is True for all values x in the iterable.",
    isSnippet: true,
  },
  {
    label: "reversed",
    kind: "Function",
    insertText: "reversed(${1:sequence})",
    documentation: "reversed(sequence) -> reverse iterator\nReturn a reverse iterator over the values of the given sequence.",
    isSnippet: true,
  },
  {
    label: "isinstance",
    kind: "Function",
    insertText: "isinstance(${1:object}, ${2:class_or_tuple})",
    documentation: "isinstance(obj, class_or_tuple, /) -> bool\nReturn whether an object is an instance of a class or subclass thereof.",
    isSnippet: true,
  },
  {
    label: "type",
    kind: "Function",
    insertText: "type(${1:object})",
    documentation: "type(object) -> the object's type",
    isSnippet: true,
  },
  {
    label: "divmod",
    kind: "Function",
    insertText: "divmod(${1:a}, ${2:b})",
    documentation: "divmod(x, y) -> (quotient, remainder)\nReturn the tuple (x//y, x%y).",
    isSnippet: true,
  },
  {
    label: "pow",
    kind: "Function",
    insertText: "pow(${1:base}, ${2:exp}, ${3:mod})",
    documentation: "pow(base, exp[, mod]) -> number\nEquivalent to base**exp with 2 arguments or (base**exp) % mod with 3 arguments.",
    isSnippet: true,
  },
  {
    label: "bin",
    kind: "Function",
    insertText: "bin(${1:number})",
    documentation: "bin(number) -> str\nReturn the binary representation of an integer with prefix '0b'.",
    isSnippet: true,
  },
  {
    label: "oct",
    kind: "Function",
    insertText: "oct(${1:number})",
    documentation: "oct(number) -> str\nReturn the octal representation of an integer with prefix '0o'.",
    isSnippet: true,
  },
  {
    label: "hex",
    kind: "Function",
    insertText: "hex(${1:number})",
    documentation: "hex(number) -> str\nReturn the hexadecimal representation of an integer with prefix '0x'.",
    isSnippet: true,
  },
  {
    label: "chr",
    kind: "Function",
    insertText: "chr(${1:i})",
    documentation: "chr(i, /) -> str\nReturn a Unicode string of one character with ordinal i; 0 <= i <= 0x10ffff.",
    isSnippet: true,
  },
  {
    label: "ord",
    kind: "Function",
    insertText: "ord(${1:c})",
    documentation: "ord(c, /) -> int\nReturn the integer ordinal of a one-character string.",
    isSnippet: true,
  },
  {
    label: "format",
    kind: "Function",
    insertText: "format(${1:value}, '${2:format_spec}')",
    documentation: "format(value[, format_spec]) -> str\nConvert a value to a formatted representation, as controlled by format_spec.",
    isSnippet: true,
  },

  // ==========================================
  // 2. STRING METHODS
  // ==========================================
  {
    label: "split",
    kind: "Method",
    insertText: "split(${1:' '})",
    documentation: "str.split(sep=None, maxsplit=-1) -> list[str]\nReturn a list of the words in the string, using sep as the delimiter string.",
    isSnippet: true,
  },
  {
    label: "rsplit",
    kind: "Method",
    insertText: "rsplit(${1:' '}, ${2:1})",
    documentation: "str.rsplit(sep=None, maxsplit=-1) -> list[str]\nReturn a list of words, scanning from the right.",
    isSnippet: true,
  },
  {
    label: "splitlines",
    kind: "Method",
    insertText: "splitlines()",
    documentation: "str.splitlines(keepends=False) -> list[str]\nReturn a list of lines in the string, breaking at line boundaries.",
    isSnippet: true,
  },
  {
    label: "join",
    kind: "Method",
    insertText: "join(${1:iterable})",
    documentation: "''.join(iterable) -> str\nConcatenate any number of strings with separator.",
    isSnippet: true,
  },
  {
    label: "strip",
    kind: "Method",
    insertText: "strip(${1:})",
    documentation: "str.strip([chars]) -> str\nReturn a copy of the string with leading and trailing whitespace/chars removed.",
    isSnippet: true,
  },
  {
    label: "lstrip",
    kind: "Method",
    insertText: "lstrip(${1:})",
    documentation: "str.lstrip([chars]) -> str\nReturn a copy with leading whitespace/chars removed.",
    isSnippet: true,
  },
  {
    label: "rstrip",
    kind: "Method",
    insertText: "rstrip(${1:})",
    documentation: "str.rstrip([chars]) -> str\nReturn a copy with trailing whitespace/chars removed.",
    isSnippet: true,
  },
  {
    label: "replace",
    kind: "Method",
    insertText: "replace(${1:old}, ${2:new})",
    documentation: "str.replace(old, new[, count]) -> str\nReturn a copy with all occurrences of substring old replaced by new.",
    isSnippet: true,
  },
  {
    label: "lower",
    kind: "Method",
    insertText: "lower()",
    documentation: "str.lower() -> str\nReturn a copy of the string converted to lowercase.",
    isSnippet: true,
  },
  {
    label: "upper",
    kind: "Method",
    insertText: "upper()",
    documentation: "str.upper() -> str\nReturn a copy of the string converted to uppercase.",
    isSnippet: true,
  },
  {
    label: "capitalize",
    kind: "Method",
    insertText: "capitalize()",
    documentation: "str.capitalize() -> str\nReturn a capitalized version of the string (first char uppercase, rest lowercase).",
    isSnippet: true,
  },
  {
    label: "title",
    kind: "Method",
    insertText: "title()",
    documentation: "str.title() -> str\nReturn a version of the string where each word is titlecased.",
    isSnippet: true,
  },
  {
    label: "swapcase",
    kind: "Method",
    insertText: "swapcase()",
    documentation: "str.swapcase() -> str\nConvert uppercase characters to lowercase and lowercase to uppercase.",
    isSnippet: true,
  },
  {
    label: "find",
    kind: "Method",
    insertText: "find(${1:sub})",
    documentation: "str.find(sub[, start[, end]]) -> int\nReturn the lowest index in S where substring sub is found. Return -1 on failure.",
    isSnippet: true,
  },
  {
    label: "rfind",
    kind: "Method",
    insertText: "rfind(${1:sub})",
    documentation: "str.rfind(sub[, start[, end]]) -> int\nReturn highest index in S where substring sub is found. Return -1 on failure.",
    isSnippet: true,
  },
  {
    label: "index",
    kind: "Method",
    insertText: "index(${1:sub})",
    documentation: "str.index(sub[, start[, end]]) -> int\nLike find() but raise ValueError when the substring is not found.",
    isSnippet: true,
  },
  {
    label: "count",
    kind: "Method",
    insertText: "count(${1:sub})",
    documentation: "str.count(sub[, start[, end]]) -> int\nReturn the number of non-overlapping occurrences of substring sub.",
    isSnippet: true,
  },
  {
    label: "startswith",
    kind: "Method",
    insertText: "startswith(${1:prefix})",
    documentation: "str.startswith(prefix[, start[, end]]) -> bool\nReturn True if S starts with the specified prefix, False otherwise.",
    isSnippet: true,
  },
  {
    label: "endswith",
    kind: "Method",
    insertText: "endswith(${1:suffix})",
    documentation: "str.endswith(suffix[, start[, end]]) -> bool\nReturn True if S ends with the specified suffix, False otherwise.",
    isSnippet: true,
  },
  {
    label: "isdigit",
    kind: "Method",
    insertText: "isdigit()",
    documentation: "str.isdigit() -> bool\nReturn True if all characters in the string are digits and there is at least one character.",
    isSnippet: true,
  },
  {
    label: "isalpha",
    kind: "Method",
    insertText: "isalpha()",
    documentation: "str.isalpha() -> bool\nReturn True if all characters in the string are alphabetic.",
    isSnippet: true,
  },
  {
    label: "isalnum",
    kind: "Method",
    insertText: "isalnum()",
    documentation: "str.isalnum() -> bool\nReturn True if all characters in the string are alphanumeric.",
    isSnippet: true,
  },
  {
    label: "isspace",
    kind: "Method",
    insertText: "isspace()",
    documentation: "str.isspace() -> bool\nReturn True if all characters in the string are whitespace.",
    isSnippet: true,
  },
  {
    label: "zfill",
    kind: "Method",
    insertText: "zfill(${1:width})",
    documentation: "str.zfill(width) -> str\nPad a numeric string with zeros on the left, to fill a field of the given width.",
    isSnippet: true,
  },
  {
    label: "center",
    kind: "Method",
    insertText: "center(${1:width})",
    documentation: "str.center(width[, fillchar]) -> str\nReturn S centered in a string of length width.",
    isSnippet: true,
  },

  // ==========================================
  // 3. LIST METHODS
  // ==========================================
  {
    label: "append",
    kind: "Method",
    insertText: "append(${1:object})",
    documentation: "list.append(object) -> None\nAppend object to the end of the list.",
    isSnippet: true,
  },
  {
    label: "extend",
    kind: "Method",
    insertText: "extend(${1:iterable})",
    documentation: "list.extend(iterable) -> None\nExtend list by appending elements from the iterable.",
    isSnippet: true,
  },
  {
    label: "insert",
    kind: "Method",
    insertText: "insert(${1:index}, ${2:object})",
    documentation: "list.insert(index, object) -> None\nInsert object before index.",
    isSnippet: true,
  },
  {
    label: "pop",
    kind: "Method",
    insertText: "pop(${1:})",
    documentation: "list.pop([index]) -> item\nRemove and return item at index (default last). Raises IndexError if list is empty.",
    isSnippet: true,
  },
  {
    label: "remove",
    kind: "Method",
    insertText: "remove(${1:value})",
    documentation: "list.remove(value) -> None\nRemove first occurrence of value. Raises ValueError if the value is not present.",
    isSnippet: true,
  },
  {
    label: "clear",
    kind: "Method",
    insertText: "clear()",
    documentation: "list.clear() -> None\nRemove all items from list.",
    isSnippet: true,
  },
  {
    label: "sort",
    kind: "Method",
    insertText: "sort(key=${1:None}, reverse=${2:False})",
    documentation: "list.sort(*, key=None, reverse=False) -> None\nSort the list in-place.",
    isSnippet: true,
  },
  {
    label: "reverse",
    kind: "Method",
    insertText: "reverse()",
    documentation: "list.reverse() -> None\nReverse *IN PLACE*.",
    isSnippet: true,
  },
  {
    label: "copy",
    kind: "Method",
    insertText: "copy()",
    documentation: "list.copy() -> list\nReturn a shallow copy of the list.",
    isSnippet: true,
  },

  // ==========================================
  // 4. DICTIONARY METHODS
  // ==========================================
  {
    label: "keys",
    kind: "Method",
    insertText: "keys()",
    documentation: "dict.keys() -> a set-like object providing a view on dict's keys.",
    isSnippet: true,
  },
  {
    label: "values",
    kind: "Method",
    insertText: "values()",
    documentation: "dict.values() -> an object providing a view on dict's values.",
    isSnippet: true,
  },
  {
    label: "items",
    kind: "Method",
    insertText: "items()",
    documentation: "dict.items() -> a set-like object providing a view on dict's (key, value) pairs.",
    isSnippet: true,
  },
  {
    label: "get",
    kind: "Method",
    insertText: "get(${1:key}, ${2:default})",
    documentation: "dict.get(key[, default]) -> D[k] if k in D, else default.",
    isSnippet: true,
  },
  {
    label: "update",
    kind: "Method",
    insertText: "update(${1:other})",
    documentation: "dict.update([E, ]**F) -> None\nUpdate D from dict/iterable E and F.",
    isSnippet: true,
  },
  {
    label: "setdefault",
    kind: "Method",
    insertText: "setdefault(${1:key}, ${2:default})",
    documentation: "dict.setdefault(key, default=None) -> D.get(key,default), also set D[key]=default if key not in D.",
    isSnippet: true,
  },

  // ==========================================
  // 5. SET METHODS
  // ==========================================
  {
    label: "add",
    kind: "Method",
    insertText: "add(${1:element})",
    documentation: "set.add(element) -> None\nAdd an element to a set. Has no effect if element is already present.",
    isSnippet: true,
  },
  {
    label: "discard",
    kind: "Method",
    insertText: "discard(${1:element})",
    documentation: "set.discard(element) -> None\nRemove an element from a set if it is a member. Do not raise error if not found.",
    isSnippet: true,
  },
  {
    label: "union",
    kind: "Method",
    insertText: "union(${1:other})",
    documentation: "set.union(*others) -> set\nReturn the union of sets as a new set (equivalent to set | other).",
    isSnippet: true,
  },
  {
    label: "intersection",
    kind: "Method",
    insertText: "intersection(${1:other})",
    documentation: "set.intersection(*others) -> set\nReturn the intersection of two sets as a new set (equivalent to set & other).",
    isSnippet: true,
  },
  {
    label: "difference",
    kind: "Method",
    insertText: "difference(${1:other})",
    documentation: "set.difference(*others) -> set\nReturn difference of two or more sets as a new set (equivalent to set - other).",
    isSnippet: true,
  },

  // ==========================================
  // 6. STANDARD MODULES & COMPETITIVE PROGRAMMING SNIPPETS
  // ==========================================
  {
    label: "input_int",
    kind: "Snippet",
    insertText: "${1:n} = int(input().strip())",
    documentation: "Read a single integer from stdin",
    isSnippet: true,
  },
  {
    label: "input_split",
    kind: "Snippet",
    insertText: "${1:a}, ${2:b} = map(int, input().split())",
    documentation: "Read space-separated integers into variables",
    isSnippet: true,
  },
  {
    label: "input_list",
    kind: "Snippet",
    insertText: "${1:arr} = list(map(int, input().split()))",
    documentation: "Read a full line of space-separated integers as a list",
    isSnippet: true,
  },
  {
    label: "input_matrix",
    kind: "Snippet",
    insertText: "${1:grid} = [list(map(int, input().split())) for _ in range(${2:n})]",
    documentation: "Read an n x m matrix of integers from stdin",
    isSnippet: true,
  },
  {
    label: "fast_io",
    kind: "Snippet",
    insertText: "import sys\ninput = sys.stdin.readline\n",
    documentation: "Fast standard I/O boilerplate for competitive programming",
    isSnippet: true,
  },
  {
    label: "main_func",
    kind: "Snippet",
    insertText: "import sys\n\ndef main():\n    ${1:pass}\n\nif __name__ == '__main__':\n    main()",
    documentation: "Standard Python application entrypoint",
    isSnippet: true,
  },
  {
    label: "for_range",
    kind: "Snippet",
    insertText: "for ${1:i} in range(${2:n}):\n    ${3:pass}",
    documentation: "For loop with range",
    isSnippet: true,
  },
  {
    label: "for_enumerate",
    kind: "Snippet",
    insertText: "for ${1:i}, ${2:val} in enumerate(${3:arr}):\n    ${4:pass}",
    documentation: "For loop with enumerate index and value",
    isSnippet: true,
  },
  {
    label: "counter",
    kind: "Snippet",
    insertText: "from collections import Counter\n${1:counts} = Counter(${2:iterable})",
    documentation: "Count element frequencies with collections.Counter",
    isSnippet: true,
  },
  {
    label: "defaultdict",
    kind: "Snippet",
    insertText: "from collections import defaultdict\n${1:d} = defaultdict(${2:list})",
    documentation: "Dictionary with default factory type (list, int, etc.)",
    isSnippet: true,
  },
  {
    label: "deque",
    kind: "Snippet",
    insertText: "from collections import deque\n${1:queue} = deque([${2:}])",
    documentation: "Fast double-ended queue for O(1) append/pop left",
    isSnippet: true,
  },
  {
    label: "heapq_min",
    kind: "Snippet",
    insertText: "import heapq\n${1:heap} = []\nheapq.heappush(${1:heap}, ${2:val})\n${3:top} = heapq.heappop(${1:heap})",
    documentation: "Min-heap operations with heapq",
    isSnippet: true,
  },
  {
    label: "binary_search",
    kind: "Snippet",
    insertText: "def binary_search(arr, target):\n    low, high = 0, len(arr) - 1\n    while low <= high:\n        mid = (low + high) // 2\n        if arr[mid] == target:\n            return mid\n        elif arr[mid] < target:\n            low = mid + 1\n        else:\n            high = mid - 1\n    return -1",
    documentation: "Standard iterative binary search algorithm",
    isSnippet: true,
  },
  {
    label: "gcd_lcm",
    kind: "Snippet",
    insertText: "import math\n\ndef gcd(a, b):\n    return math.gcd(a, b)\n\ndef lcm(a, b):\n    return math.lcm(a, b)",
    documentation: "Greatest Common Divisor & Least Common Multiple",
    isSnippet: true,
  },
  {
    label: "is_prime",
    kind: "Snippet",
    insertText: "def is_prime(n):\n    if n < 2:\n        return False\n    for i in range(2, int(n**0.5) + 1):\n        if n % i == 0:\n            return False\n    return True",
    documentation: "Prime number test in O(sqrt(n))",
    isSnippet: true,
  },
  {
    label: "sieve_primes",
    kind: "Snippet",
    insertText: "def sieve(n):\n    is_prime = [True] * (n + 1)\n    is_prime[0] = is_prime[1] = False\n    for i in range(2, int(n**0.5) + 1):\n        if is_prime[i]:\n            for j in range(i * i, n + 1, i):\n                is_prime[j] = False\n    return [i for i, prime in enumerate(is_prime) if prime]",
    documentation: "Sieve of Eratosthenes to generate primes up to n",
    isSnippet: true,
  },
  {
    label: "recursion_limit",
    kind: "Snippet",
    insertText: "import sys\nsys.setrecursionlimit(${1:200000})\n",
    documentation: "Increase Python recursion limit for deep DFS",
    isSnippet: true,
  },
  {
    label: "bfs_template",
    kind: "Snippet",
    insertText: "from collections import deque\n\ndef bfs(start, graph):\n    visited = {start}\n    queue = deque([start])\n    while queue:\n        curr = queue.popleft()\n        for neighbor in graph[curr]:\n            if neighbor not in visited:\n                visited.add(neighbor)\n                queue.append(neighbor)",
    documentation: "Breadth-First Search traversal template",
    isSnippet: true,
  },
  {
    label: "dfs_template",
    kind: "Snippet",
    insertText: "def dfs(node, graph, visited):\n    visited.add(node)\n    for neighbor in graph[node]:\n        if neighbor not in visited:\n            dfs(neighbor, graph, visited)",
    documentation: "Depth-First Search recursive traversal template",
    isSnippet: true,
  },
];
